# 포트번호 설정
server:
  port: 80

# 애플리케이션 이름 설정
spring:
  application:
    name: workus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workus?useSSL=false
    username: user1
    password: zxcv1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# 첨부파일 업로드 폴더
upload:
  directory:
    board: "C:/projects/final-repository"
