# 포트번호 설정
server:
  port: 80

# 애플리케이션 이름 설정
spring:
  application:
    name: workus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-2.crzth3asbpqd.ap-northeast-2.rds.amazonaws.com:3306/workus?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: hta
    password: Zxcv!234!!
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# 첨부파일 업로드 폴더
upload:
  directory:
    board: "C:/projects/final-repository"

# mybatis 설정
mybatis:
  mapper-locations:
    - mybatis/mappers/*.xml
  configuration:
    jdbc-type-for-null: NULL
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  type-aliases-package: com.example.workus.**.vo,com.example.workus.**.dto

# 로그레벨 출력
logging:
  level:
    root: info
    com.example.workus.chat: debug